import type { NextPage } from 'next'
import Head from 'next/head'
import TodosForm from '../components/todos'
import UsersForm from '../components/users'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>App de prueba</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Todos</h1>
      <TodosForm />
      <h1>Users</h1>
      <UsersForm />
    </div>
  )
}

export default Home
